# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main3.ui'
#
# Created: Thu May 13 16:39:55 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 10, 141, 541))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.Tabs = QtGui.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(140, 10, 641, 541))
        self.Tabs.setObjectName("Tabs")
        self.geometry = QtGui.QWidget()
        self.geometry.setObjectName("geometry")
        self.createGeom = QtGui.QPushButton(self.geometry)
        self.createGeom.setGeometry(QtCore.QRect(10, 0, 101, 31))
        self.createGeom.setObjectName("createGeom")
        self.importGeom = QtGui.QPushButton(self.geometry)
        self.importGeom.setGeometry(QtCore.QRect(120, 0, 101, 31))
        self.importGeom.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.importGeom.setObjectName("importGeom")
        self.exportGeom = QtGui.QPushButton(self.geometry)
        self.exportGeom.setGeometry(QtCore.QRect(230, 0, 101, 31))
        self.exportGeom.setObjectName("exportGeom")
        self.interpolateGeom = QtGui.QPushButton(self.geometry)
        self.interpolateGeom.setGeometry(QtCore.QRect(340, 0, 101, 31))
        self.interpolateGeom.setObjectName("interpolateGeom")
        self.layoutWidget = QtGui.QWidget(self.geometry)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 31, 621, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listSections = QtGui.QListWidget(self.splitter)
        self.listSections.setObjectName("listSections")
        self.tableSectionCoord = QtGui.QTableView(self.splitter)
        self.tableSectionCoord.setObjectName("tableSectionCoord")
        self.verticalLayout.addWidget(self.splitter)
        self.sectionGraphics = QtGui.QGraphicsView(self.layoutWidget)
        self.sectionGraphics.setObjectName("sectionGraphics")
        self.verticalLayout.addWidget(self.sectionGraphics)
        self.Tabs.addTab(self.geometry, "")
        self.ics = QtGui.QWidget()
        self.ics.setObjectName("ics")
        self.exportIcs = QtGui.QPushButton(self.ics)
        self.exportIcs.setGeometry(QtCore.QRect(220, 0, 101, 31))
        self.exportIcs.setObjectName("exportIcs")
        self.importIcs = QtGui.QPushButton(self.ics)
        self.importIcs.setGeometry(QtCore.QRect(110, 0, 101, 31))
        self.importIcs.setObjectName("importIcs")
        self.createIcs = QtGui.QPushButton(self.ics)
        self.createIcs.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.createIcs.setObjectName("createIcs")
        self.Tabs.addTab(self.ics, "")
        self.bcs = QtGui.QWidget()
        self.bcs.setObjectName("bcs")
        self.exportBcs = QtGui.QPushButton(self.bcs)
        self.exportBcs.setGeometry(QtCore.QRect(220, 0, 101, 31))
        self.exportBcs.setObjectName("exportBcs")
        self.importBcs = QtGui.QPushButton(self.bcs)
        self.importBcs.setGeometry(QtCore.QRect(110, 0, 101, 31))
        self.importBcs.setObjectName("importBcs")
        self.createBcs = QtGui.QPushButton(self.bcs)
        self.createBcs.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.createBcs.setObjectName("createBcs")
        self.Tabs.addTab(self.bcs, "")
        self.parameters = QtGui.QWidget()
        self.parameters.setObjectName("parameters")
        self.exportParam = QtGui.QPushButton(self.parameters)
        self.exportParam.setGeometry(QtCore.QRect(220, 0, 101, 31))
        self.exportParam.setObjectName("exportParam")
        self.importParam = QtGui.QPushButton(self.parameters)
        self.importParam.setGeometry(QtCore.QRect(110, 0, 101, 31))
        self.importParam.setObjectName("importParam")
        self.createParam = QtGui.QPushButton(self.parameters)
        self.createParam.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.createParam.setObjectName("createParam")
        self.Tabs.addTab(self.parameters, "")
        self.simulation = QtGui.QWidget()
        self.simulation.setObjectName("simulation")
        self.stopSimulation = QtGui.QPushButton(self.simulation)
        self.stopSimulation.setGeometry(QtCore.QRect(110, 0, 101, 31))
        self.stopSimulation.setObjectName("stopSimulation")
        self.runSimulation = QtGui.QPushButton(self.simulation)
        self.runSimulation.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.runSimulation.setObjectName("runSimulation")
        self.Tabs.addTab(self.simulation, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 24))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setObjectName("action_Load")
        self.importGeometry = QtGui.QAction(MainWindow)
        self.importGeometry.setCheckable(True)
        self.importGeometry.setObjectName("importGeometry")
        self.menuProject.addAction(self.action_New)
        self.menuProject.addAction(self.action_Load)
        self.menubar.addAction(self.menuProject.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.listSections, QtCore.SIGNAL("currentRowChanged(int)"), MainWindow.itemChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "openRiver", None, QtGui.QApplication.UnicodeUTF8))
        self.createGeom.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.importGeom.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.exportGeom.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolateGeom.setText(QtGui.QApplication.translate("MainWindow", "Interpolate", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.geometry), QtGui.QApplication.translate("MainWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.exportIcs.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.importIcs.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.createIcs.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ics), QtGui.QApplication.translate("MainWindow", "ICs", None, QtGui.QApplication.UnicodeUTF8))
        self.exportBcs.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.importBcs.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.createBcs.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.bcs), QtGui.QApplication.translate("MainWindow", "BCs", None, QtGui.QApplication.UnicodeUTF8))
        self.exportParam.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.importParam.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.createParam.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.parameters), QtGui.QApplication.translate("MainWindow", "Model Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.stopSimulation.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.runSimulation.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.simulation), QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.importGeometry.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))

